<?php
require_once ROOT_PATH . '/siteConfig.php';
require_once ROOT_PATH . '/includes/header.php';
require_once ROOT_PATH . '/includes/navbar.php';

?>

<body class="theme-light">
    <section class="hero-section" id="hero">
        <video loading="lazy" autoplay muted loop playsinline>
            <source src="<?= BASE_URL; ?>assets/videos/hero.mp4" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <div class="hero-overlay"></div>
        <div class="hero-content">

            <div class="hero-left hero-side">
                <div class="hero-title-con" id="heroTitleCon">
                </div>
                <div class="hero_text">
                    <p id="hero-text">
                        <span>𝗪𝗲 𝗼𝗳𝗳𝗲𝗿 𝗮 𝘄𝗶𝗱𝗲 𝗿𝗮𝗻𝗴𝗲 𝗼𝗳</span> <span>𝙋𝙞𝙯𝙯𝙖🍕</span> <span>𝙎𝙝𝙖𝙬𝙖𝙧𝙢𝙖🌯</span> <span>𝙄𝙘𝙚 𝙘𝙧𝙚𝙖𝙢🍦</span>
                    </p>
                </div>
                <a href="#menuGrid" id="hero-btn" class="btn btn-primary hero-btn mt-3">Order Now</a>
            </div>

            <div class="hero-right hero-side" id="hero-right">
            </div>
        </div>
    </section>

    <!-- Featured Menu / Popular Items -->
    <section id="menu" class="section-pad">
        <div class="container">
            <div class="d-flex flex-wrap justify-content-between align-items-end mb-3">
                <div class="w-100">
                    <h2 class="section-title" data-aos="fade-right">Our Menu</h2>
                    <p class="section-sub" data-aos="fade-right" data-aos-delay="100">Select your Favourite Items.</p>
                </div>
                <div>
                    <section class="category-tabs w-100" id="categoryTabs"></section>
                </div>
            </div>

            <section class="menu-grid row g-3 d-flex" id="menuGrid"></section>
            <div class="pagination" id="pagination"></div>
            <div class="no-data" id="no-data"></div>
        </div>
    </section>
    <section class="bg-light">
        <!-- Build Your Pizza (Interactive) -->
        <section class="section-pad" id="buildYourPizza">
            <div class="container">
                <h2 class="section-title mb-3" data-aos="fade-up">Build Your Pizza</h2>
                <div class="row g-4">
                    <div class="col-sm-6 col-lg-6" data-aos="fade-right">
                        <div class="builder">
                            <div class="row g-3">
                                <div class="col-md-6">
                                    <label class="form-label fw-bold">Select Pizza</label>
                                    <select id="pizzaSelect" class="form-select">
                                    </select>

                                </div>

                                <div class="col-md-6">
                                    <label class="form-label fw-bold">Barbecue Sauce</label>
                                    <select id="crustSelect" class="form-select">
                                        <option value="beneath" data-price="0" selected>Beneath</option>
                                        <option value="ontop" data-price="0">Ontop</option>
                                        <option value="none" data-price="0">None</option>
                                    </select>
                                </div>
                                <div class="mt-3 mb-3 w-100 col-12" id="sizesBox"></div>
                                <div class="col-12">
                                    <label class="form-label fw-bold">Extras</label>
                                    <div class="d-flex flex-wrap gap-2" id="toppingsWrap">
                                        <!-- generated by JS -->
                                    </div>
                                </div>

                                <div class="col-12 d-flex align-items-center justify-content-between gap-2 flex-wrap builder-summary">
                                    <div class="builder-total">
                                        <div class="text-muted small">Estimated total</div>
                                        <div class="h4 mb-0"><span id="builderTotal">0</span></div>
                                    </div>

                                    <div class="builder-img">
                                        <img loading="lazy" src="<?= BASE_URL; ?>assets/images/hero/pizza2.png" alt="Pizza" class="product-image spin">
                                    </div>

                                    <button id="builderAddToCart" class="btn btn-primary addToCart builder-btn">
                                        Add to Order
                                    </button>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6" data-aos="fade-left">
                        <div class="p-3s rounded-4 h-100 d-flex align-items-center justify-content-center bg-white overflow-hidden">
                            <video id="buildPizVideo" class="w-100 h-100 object-fit-cover rounded-4" loading="lazy" autoplay muted loop playsinline>
                                <source src="<?= BASE_URL; ?>assets/videos/build.mp4" type="video/mp4">
                                Your browser does not support the video tag.
                            </video>
                        </div>
                        <script>
                            const heroVideo = document.getElementById('buildPizVideo');
                            heroVideo.addEventListener('ended', () => {
                                heroVideo.currentTime = 0;
                                heroVideo.play();
                            });
                        </script>
                    </div>

                </div>
            </div>
        </section>
    </section>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.5/css/lightbox.min.css" />


    <!-- How it Works -->
    <section id="howItWorks" class="section-pad">
        <div class="container">
            <h2 class="section-title mb-4" data-aos="fade-up">How We Serve You</h2>
            <div class="row g-4">
                <div class="col-md-3" data-aos="fade-up">
                    <div class="hiw-step h-100">
                        <div class="num mb-2">1</div>
                        <h6>Choose Your Cravings</h6>
                        <p class="mb-0 text-muted">Pick your Preferred Pizza, Shawarma, Drinks, etc.</p>
                    </div>
                </div>
                <div class="col-md-3" data-aos="fade-up" data-aos-delay="100">
                    <div class="hiw-step h-100">
                        <div class="num mb-2">2</div>
                        <h6>Customize It</h6>
                        <p class="mb-0 text-muted">Choose Sizes, toppings & extras in real-time.</p>
                    </div>
                </div>
                <div class="col-md-3" data-aos="fade-up" data-aos-delay="150">
                    <div class="hiw-step h-100">
                        <div class="num mb-2">3</div>
                        <h6>Secure Checkout</h6>
                        <p class="mb-0 text-muted">Pay securely using your preferred payment method.</p>
                    </div>
                </div>
                <div class="col-md-3" data-aos="fade-up" data-aos-delay="200">
                    <div class="hiw-step h-100">
                        <div class="num mb-2">4</div>
                        <h6>Fast Delivery</h6>
                        <p class="mb-0 text-muted">Our delivery is super fast, we leave Sonic in the dust.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Testimonials Slider -->


    <section id="testimonialSection" class="section-pad">
        <div class="container">
            <section class="testimonial-section">
                <h2 class="testimonial-title">What Our Customers Say 💬</h2>

                <!-- Swiper -->
                <div class="swiper mySwiper">
                    <div class="swiper-wrapper">
                        <!-- Testimonial images -->
                        <?php for ($i = 1; $i <= 15; $i++): ?>
                            <a href="<?php echo BASE_URL; ?>assets/images/testimonials/<?= $i ?>.jpg" class="testimonial-lightbox swiper-slide" data-lightbox="testimonials" data-title="Testimonial <?= $i ?>">
                                <img loading="lazy" src="<?php echo BASE_URL; ?>assets/images/testimonials/<?= $i ?>.jpg" alt="Testimonial <?= $i ?>" />
                            </a>

                        <?php endfor; ?>

                    </div>


                    <!-- Swiper controls -->
                    <div class="swiper-pagination"></div>
                    <div class="swiper-button-next"></div>
                    <div class="swiper-button-prev"></div>
                </div>
            </section>

        </div>
    </section>

    <!-- About / Our Story (Parallax) -->
    <section id="aboutSection">
        <div class="about section-pad">
            <div class="container">
                <div class="row align-items-center g-4">
                    <div class="col-lg-5">
                        <h2 class="section-title">Our Story</h2>
                        <div style="text-align: justify;">
                            <p class="mb-3 text-white-100">
                                Pizza Square Nigeria brand launched in 2020 as a proudly Nigerian pizza brand.
                            </p>
                            <p class="mb-3 text-white-100">
                                From a modest kitchen, the company developed a distinctive square crust and an Italian curated and inspired menu, incorporating regional and intensely flavors, recipes and standards to reflect Africa's diversity and global presence.
                            </p>
                            <p class="mb-3 text-white-100">
                                The brand’s mission is to serve over 100,000 pizzas annually, delivering consistent quality, community engagement, and a dependable, nationwide experience that embodies Nigerian pride.
                            </p>
                        </div>

                    </div>
                    <div class="col-lg-7">
                        <div class="row g-3">
                            <div class="p-3s rounded-4 h-100 d-flex align-items-center justify-content-center bg-white overflow-hidden">
                                <video loading="lazy" class="w-100 h-100 object-fit-cover rounded-4" autoplay muted loop playsinline>
                                    <source src="<?= BASE_URL; ?>assets/videos/hero.mp4" type="video/mp4">
                                    Your browser does not support the video tag.
                                </video>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- Location & Delivery Map -->
    <section id="track" class="section-pad">
        <div class="container">
            <div class="row g-4">
                <div class="col-lg-6" data-aos="fade-right">
                    <h2 class="section-title">Locate us</h2>
                    <p class="section-sub">We deliver across the city. Check coverage and pickup spots.</p>
                    <div class="map-card">
                        <iframe
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3962.4851841666217!2d7.52197!3d6.46017!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1044a35c9f1a7e05%3A0x49e604a5b7d0ed43!2sNew%20Haven%2C%20Enugu!5e0!3m2!1sen!2sng!4v1727455643210"
                            width="100%" height="450"
                            style="border:0;"
                            allowfullscreen=""
                            loading="lazy"
                            referrerpolicy="no-referrer-when-downgrade">
                        </iframe>


                    </div>
                </div>
                <div class="col-lg-6" data-aos="fade-left">
                    <div class="list-group shadow-sm">
                        <a href="https://share.google/U3qIHrqygnIODiNdn" target="_blank">
                            <div class="list-group-item d-flex align-items-center"><i class="fa-solid fa-store me-3 text-primary"></i>
                                <div><strong><?= COMPANY_ADDRESS ?></strong>
                                    <div class="text-muted small">Open 10:00 – 22:00</div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    

    <!-- Instagram / Social Feed -->
    <section id="followSocials" class="section-pad">
        <div class="container">
            <div class="d-flex w-100 flex-wrap align-items-end justify-content-center justify-content-md-between text-center text-md-start gap-3">
                <div>
                    <h2 class="section-title">From Our Social Media</h2>
                    <p class="section-sub">Tag <strong>@pizzasquareng</strong> to get featured.</p>
                </div>
                <div class="d-flex gap-3 flex-wrap justify-content-center justify-content-md-start">
                    <a href="https://www.instagram.com/pizzasquareng" class="btn btn-ghost">Instagram</a>
                    <a href="https://web.facebook.com/pizzasquareng/" class="btn btn-ghost">Facebook</a>
                    <a href="https://www.tiktok.com/@pizzasquareng" class="btn btn-ghost">Tiktok</a>
                    <a href="https://x.com/pizzasquareng" class="btn btn-ghost">X </a>

                </div>
            </div>

            <div class="row g-3 mt-4">
                <?php for ($i = 1; $i <= 6; $i++): ?>
                    <div class="col-6 col-md-3" data-aos="fade-up">
                        <div class="ig-card bounce-card"><img loading="lazy" src="<?php echo BASE_URL; ?>assets/images/socials/<?= $i ?>.png" alt="ig<?= $i ?>"></div>
                    </div>
                <?php endfor; ?>


            </div>
        </div>
        <div id="reelsContainer"></div>

    </section>
    <!-- === MODAL STRUCTURE === -->
    <div class="modal-overlay" id="promoModal">
        <div class="promo-modal">
            <button class="close-btn" id="closePromo">&times;</button>
            <img class="header-image" src="<?php echo BASE_URL; ?>assets/images/handcrop.jpg"
                alt="Pizza App Icon" />
            <p class="heading">Introducing <span>Pizza Square Mobile App!</span></p>
            <p>Enjoy Smoother and Faster Orders!. Our mobile app is coming soon to Google Play and iOS App Stores!</p>
            <div class="store-buttons">
                <a href="#" class="store-btn google">
                    <img src="<?php echo BASE_URL; ?>assets/images/google-play-and-apple-app-store-logos-22.png" alt="Google Play">
                </a>

            </div>
        </div>
    </div>
    <?php require_once ROOT_PATH . '/includes/footer-links.php'; ?>
    <?php require_once ROOT_PATH . '/includes/footer.php'; ?>
    <script type="module" src="<?php echo BASE_URL; ?>assets/src/Pages/LandingPage.js"></script>

    <!-- Swiper JS -->
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <!-- Lightbox2 JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.4/js/lightbox.min.js"></script>


    <script>
        const swiper = new Swiper(".mySwiper", {
            loop: true, // Infinite loop
            autoplay: {
                delay: 3000, // Auto-slide every 3s
                disableOnInteraction: false,
            },
            speed: 800,
            centeredSlides: true,
            slidesPerView: 1,
            spaceBetween: 20,
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
            breakpoints: {
                768: {
                    slidesPerView: 2, // show 2 slides on tablets/desktops
                },
            },
        });
    </script>

    <script>
        // === Modal Auto Display ===
        window.addEventListener("load", () => {
            const modal = document.getElementById("promoModal");
            const closeBtn = document.getElementById("closePromo");

            // Show after a short delay (e.g. 1s)
            setTimeout(() => {
                modal.classList.add("active");
            }, 1000);

            // Close when button clicked or overlay clicked
            closeBtn.addEventListener("click", () => modal.classList.remove("active"));
            modal.addEventListener("click", (e) => {
                if (e.target === modal) modal.classList.remove("active");
            });
        });
    </script>
</body>

</html>